// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project_PiggyPro.Data;

#nullable disable

namespace Project_PiggyPro.Migrations
{
    [DbContext(typeof(Project_PiggyProContext))]
    [Migration("20260106091720_SeedUserRole2")]
    partial class SeedUserRole2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ad2bcf0c-20db-474f-8407-5a6b159518ba",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "bd2bcf0c-20db-474f-8407-5a6b159518bb",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Project_PiggyPro.Data.Project_PiggyProUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Project_PiggyPro.Domain.Budget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<double>("BudgetAmount")
                        .HasColumnType("float");

                    b.Property<string>("BudgetPeriod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("NeedsPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SavingsPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("WantsPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Budget");
                });

            modelBuilder.Entity("Project_PiggyPro.Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSystemCategory")
                        .HasColumnType("bit");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Housing & Rent",
                            CategoryType = "Expense",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 6, 17, 17, 17, 841, DateTimeKind.Local).AddTicks(1110),
                            DateUpdated = new DateTime(2026, 1, 6, 17, 17, 17, 841, DateTimeKind.Local).AddTicks(1158),
                            IsSystemCategory = true,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Groceries",
                            CategoryType = "Expense",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 6, 17, 17, 17, 841, DateTimeKind.Local).AddTicks(1166),
                            DateUpdated = new DateTime(2026, 1, 6, 17, 17, 17, 841, DateTimeKind.Local).AddTicks(1168),
                            IsSystemCategory = true,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Utilities",
                            CategoryType = "Expense",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 6, 17, 17, 17, 841, DateTimeKind.Local).AddTicks(1172),
                            DateUpdated = new DateTime(2026, 1, 6, 17, 17, 17, 841, DateTimeKind.Local).AddTicks(1173),
                            IsSystemCategory = true,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Transportation",
                            CategoryType = "Expense",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 6, 17, 17, 17, 841, DateTimeKind.Local).AddTicks(1176),
                            DateUpdated = new DateTime(2026, 1, 6, 17, 17, 17, 841, DateTimeKind.Local).AddTicks(1177),
                            IsSystemCategory = true,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "Healthcare",
                            CategoryType = "Expense",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 6, 17, 17, 17, 841, DateTimeKind.Local).AddTicks(1180),
                            DateUpdated = new DateTime(2026, 1, 6, 17, 17, 17, 841, DateTimeKind.Local).AddTicks(1182),
                            IsSystemCategory = true,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 6,
                            CategoryName = "Dining Out",
                            CategoryType = "Expense",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 6, 17, 17, 17, 841, DateTimeKind.Local).AddTicks(1185),
                            DateUpdated = new DateTime(2026, 1, 6, 17, 17, 17, 841, DateTimeKind.Local).AddTicks(1186),
                            IsSystemCategory = true,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 7,
                            CategoryName = "Entertainment",
                            CategoryType = "Expense",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 6, 17, 17, 17, 841, DateTimeKind.Local).AddTicks(1189),
                            DateUpdated = new DateTime(2026, 1, 6, 17, 17, 17, 841, DateTimeKind.Local).AddTicks(1190),
                            IsSystemCategory = true,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 8,
                            CategoryName = "Shopping",
                            CategoryType = "Expense",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 6, 17, 17, 17, 841, DateTimeKind.Local).AddTicks(1193),
                            DateUpdated = new DateTime(2026, 1, 6, 17, 17, 17, 841, DateTimeKind.Local).AddTicks(1195),
                            IsSystemCategory = true,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 9,
                            CategoryName = "Hobbies",
                            CategoryType = "Expense",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 6, 17, 17, 17, 841, DateTimeKind.Local).AddTicks(1198),
                            DateUpdated = new DateTime(2026, 1, 6, 17, 17, 17, 841, DateTimeKind.Local).AddTicks(1199),
                            IsSystemCategory = true,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 10,
                            CategoryName = "Savings",
                            CategoryType = "Expense",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 6, 17, 17, 17, 841, DateTimeKind.Local).AddTicks(1332),
                            DateUpdated = new DateTime(2026, 1, 6, 17, 17, 17, 841, DateTimeKind.Local).AddTicks(1334),
                            IsSystemCategory = true,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 11,
                            CategoryName = "Investments",
                            CategoryType = "Expense",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 6, 17, 17, 17, 841, DateTimeKind.Local).AddTicks(1337),
                            DateUpdated = new DateTime(2026, 1, 6, 17, 17, 17, 841, DateTimeKind.Local).AddTicks(1338),
                            IsSystemCategory = true,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 12,
                            CategoryName = "Emergency Fund",
                            CategoryType = "Expense",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 6, 17, 17, 17, 841, DateTimeKind.Local).AddTicks(1341),
                            DateUpdated = new DateTime(2026, 1, 6, 17, 17, 17, 841, DateTimeKind.Local).AddTicks(1342),
                            IsSystemCategory = true,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 13,
                            CategoryName = "Other Expenses",
                            CategoryType = "Expense",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 6, 17, 17, 17, 841, DateTimeKind.Local).AddTicks(1345),
                            DateUpdated = new DateTime(2026, 1, 6, 17, 17, 17, 841, DateTimeKind.Local).AddTicks(1347),
                            IsSystemCategory = true,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 14,
                            CategoryName = "Salary",
                            CategoryType = "Income",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 6, 17, 17, 17, 841, DateTimeKind.Local).AddTicks(1350),
                            DateUpdated = new DateTime(2026, 1, 6, 17, 17, 17, 841, DateTimeKind.Local).AddTicks(1351),
                            IsSystemCategory = true,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 15,
                            CategoryName = "Freelance",
                            CategoryType = "Income",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 6, 17, 17, 17, 841, DateTimeKind.Local).AddTicks(1354),
                            DateUpdated = new DateTime(2026, 1, 6, 17, 17, 17, 841, DateTimeKind.Local).AddTicks(1356),
                            IsSystemCategory = true,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 16,
                            CategoryName = "Investment Income",
                            CategoryType = "Income",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 6, 17, 17, 17, 841, DateTimeKind.Local).AddTicks(1359),
                            DateUpdated = new DateTime(2026, 1, 6, 17, 17, 17, 841, DateTimeKind.Local).AddTicks(1360),
                            IsSystemCategory = true,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 17,
                            CategoryName = "Gift/Bonus",
                            CategoryType = "Income",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 6, 17, 17, 17, 841, DateTimeKind.Local).AddTicks(1363),
                            DateUpdated = new DateTime(2026, 1, 6, 17, 17, 17, 841, DateTimeKind.Local).AddTicks(1365),
                            IsSystemCategory = true,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 18,
                            CategoryName = "Other Income",
                            CategoryType = "Income",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 6, 17, 17, 17, 841, DateTimeKind.Local).AddTicks(1368),
                            DateUpdated = new DateTime(2026, 1, 6, 17, 17, 17, 841, DateTimeKind.Local).AddTicks(1369),
                            IsSystemCategory = true,
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("Project_PiggyPro.Domain.Goal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CurrentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("GoalName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TargetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TargetDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Goal");
                });

            modelBuilder.Entity("Project_PiggyPro.Domain.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotificationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("Project_PiggyPro.Domain.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Transaction");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Project_PiggyPro.Data.Project_PiggyProUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Project_PiggyPro.Data.Project_PiggyProUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project_PiggyPro.Data.Project_PiggyProUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Project_PiggyPro.Data.Project_PiggyProUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
