// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project_PiggyPro.Data;

#nullable disable

namespace Project_PiggyPro.Migrations
{
    [DbContext(typeof(Project_PiggyProContext))]
    [Migration("20260105053939_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Project_PiggyPro.Domain.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppUser");
                });

            modelBuilder.Entity("Project_PiggyPro.Domain.Budget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<double>("BudgetAmount")
                        .HasColumnType("float");

                    b.Property<string>("BudgetPeriod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("NeedsPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SavingsPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("WantsPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Budget");
                });

            modelBuilder.Entity("Project_PiggyPro.Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSystemCategory")
                        .HasColumnType("bit");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Housing & Rent",
                            CategoryType = "Expense",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 5, 13, 39, 37, 582, DateTimeKind.Local).AddTicks(7336),
                            DateUpdated = new DateTime(2026, 1, 5, 13, 39, 37, 582, DateTimeKind.Local).AddTicks(7363),
                            IsSystemCategory = true,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Groceries",
                            CategoryType = "Expense",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 5, 13, 39, 37, 582, DateTimeKind.Local).AddTicks(7366),
                            DateUpdated = new DateTime(2026, 1, 5, 13, 39, 37, 582, DateTimeKind.Local).AddTicks(7367),
                            IsSystemCategory = true,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Utilities",
                            CategoryType = "Expense",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 5, 13, 39, 37, 582, DateTimeKind.Local).AddTicks(7369),
                            DateUpdated = new DateTime(2026, 1, 5, 13, 39, 37, 582, DateTimeKind.Local).AddTicks(7370),
                            IsSystemCategory = true,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Transportation",
                            CategoryType = "Expense",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 5, 13, 39, 37, 582, DateTimeKind.Local).AddTicks(7372),
                            DateUpdated = new DateTime(2026, 1, 5, 13, 39, 37, 582, DateTimeKind.Local).AddTicks(7373),
                            IsSystemCategory = true,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "Healthcare",
                            CategoryType = "Expense",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 5, 13, 39, 37, 582, DateTimeKind.Local).AddTicks(7375),
                            DateUpdated = new DateTime(2026, 1, 5, 13, 39, 37, 582, DateTimeKind.Local).AddTicks(7376),
                            IsSystemCategory = true,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 6,
                            CategoryName = "Dining Out",
                            CategoryType = "Expense",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 5, 13, 39, 37, 582, DateTimeKind.Local).AddTicks(7378),
                            DateUpdated = new DateTime(2026, 1, 5, 13, 39, 37, 582, DateTimeKind.Local).AddTicks(7379),
                            IsSystemCategory = true,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 7,
                            CategoryName = "Entertainment",
                            CategoryType = "Expense",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 5, 13, 39, 37, 582, DateTimeKind.Local).AddTicks(7381),
                            DateUpdated = new DateTime(2026, 1, 5, 13, 39, 37, 582, DateTimeKind.Local).AddTicks(7382),
                            IsSystemCategory = true,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 8,
                            CategoryName = "Shopping",
                            CategoryType = "Expense",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 5, 13, 39, 37, 582, DateTimeKind.Local).AddTicks(7384),
                            DateUpdated = new DateTime(2026, 1, 5, 13, 39, 37, 582, DateTimeKind.Local).AddTicks(7385),
                            IsSystemCategory = true,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 9,
                            CategoryName = "Hobbies",
                            CategoryType = "Expense",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 5, 13, 39, 37, 582, DateTimeKind.Local).AddTicks(7387),
                            DateUpdated = new DateTime(2026, 1, 5, 13, 39, 37, 582, DateTimeKind.Local).AddTicks(7388),
                            IsSystemCategory = true,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 10,
                            CategoryName = "Savings",
                            CategoryType = "Expense",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 5, 13, 39, 37, 582, DateTimeKind.Local).AddTicks(7390),
                            DateUpdated = new DateTime(2026, 1, 5, 13, 39, 37, 582, DateTimeKind.Local).AddTicks(7391),
                            IsSystemCategory = true,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 11,
                            CategoryName = "Investments",
                            CategoryType = "Expense",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 5, 13, 39, 37, 582, DateTimeKind.Local).AddTicks(7393),
                            DateUpdated = new DateTime(2026, 1, 5, 13, 39, 37, 582, DateTimeKind.Local).AddTicks(7394),
                            IsSystemCategory = true,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 12,
                            CategoryName = "Emergency Fund",
                            CategoryType = "Expense",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 5, 13, 39, 37, 582, DateTimeKind.Local).AddTicks(7396),
                            DateUpdated = new DateTime(2026, 1, 5, 13, 39, 37, 582, DateTimeKind.Local).AddTicks(7397),
                            IsSystemCategory = true,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 13,
                            CategoryName = "Other Expenses",
                            CategoryType = "Expense",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 5, 13, 39, 37, 582, DateTimeKind.Local).AddTicks(7400),
                            DateUpdated = new DateTime(2026, 1, 5, 13, 39, 37, 582, DateTimeKind.Local).AddTicks(7400),
                            IsSystemCategory = true,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 14,
                            CategoryName = "Salary",
                            CategoryType = "Income",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 5, 13, 39, 37, 582, DateTimeKind.Local).AddTicks(7402),
                            DateUpdated = new DateTime(2026, 1, 5, 13, 39, 37, 582, DateTimeKind.Local).AddTicks(7403),
                            IsSystemCategory = true,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 15,
                            CategoryName = "Freelance",
                            CategoryType = "Income",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 5, 13, 39, 37, 582, DateTimeKind.Local).AddTicks(7405),
                            DateUpdated = new DateTime(2026, 1, 5, 13, 39, 37, 582, DateTimeKind.Local).AddTicks(7406),
                            IsSystemCategory = true,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 16,
                            CategoryName = "Investment Income",
                            CategoryType = "Income",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 5, 13, 39, 37, 582, DateTimeKind.Local).AddTicks(7408),
                            DateUpdated = new DateTime(2026, 1, 5, 13, 39, 37, 582, DateTimeKind.Local).AddTicks(7409),
                            IsSystemCategory = true,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 17,
                            CategoryName = "Gift/Bonus",
                            CategoryType = "Income",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 5, 13, 39, 37, 582, DateTimeKind.Local).AddTicks(7411),
                            DateUpdated = new DateTime(2026, 1, 5, 13, 39, 37, 582, DateTimeKind.Local).AddTicks(7412),
                            IsSystemCategory = true,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 18,
                            CategoryName = "Other Income",
                            CategoryType = "Income",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 5, 13, 39, 37, 582, DateTimeKind.Local).AddTicks(7414),
                            DateUpdated = new DateTime(2026, 1, 5, 13, 39, 37, 582, DateTimeKind.Local).AddTicks(7415),
                            IsSystemCategory = true,
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("Project_PiggyPro.Domain.Goal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CurrentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("GoalName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TargetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TargetDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Goal");
                });

            modelBuilder.Entity("Project_PiggyPro.Domain.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotificationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("Project_PiggyPro.Domain.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Transaction");
                });
#pragma warning restore 612, 618
        }
    }
}
