// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project_PiggyPro.Data;

#nullable disable

namespace Project_PiggyPro.Migrations
{
    [DbContext(typeof(Project_PiggyProContext))]
    [Migration("20260116075852_AddCategotyToBudget")]
    partial class AddCategotyToBudget
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ad2bcf0c-20db-474f-8407-5a6b159518ba",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "bd2bcf0c-20db-474f-8407-5a6b159518bb",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "3781efa7-66dc-47f0-860f-e506d04102e4",
                            RoleId = "ad2bcf0c-20db-474f-8407-5a6b159518ba"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Project_PiggyPro.Data.Project_PiggyProUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "3781efa7-66dc-47f0-860f-e506d04102e4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1d95127a-857c-4d1e-b443-32474406ef39",
                            CreatedAt = new DateTime(2026, 1, 16, 7, 58, 51, 71, DateTimeKind.Utc).AddTicks(7193),
                            Email = "admin@localhost.com",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@LOCALHOST.COM",
                            NormalizedUserName = "ADMIN@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPeFABql8mLZAVbgdX70hOcqAbWGuQcf5mQUStS6VCpldPXIJoLmKFlwmP9IVC0B/Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3ec3e10a-ec95-40fe-8495-580017ab5833",
                            TwoFactorEnabled = false,
                            UserName = "admin@localhost.com"
                        });
                });

            modelBuilder.Entity("Project_PiggyPro.Domain.Budget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AllocatedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BucketType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("BudgetAmount")
                        .HasColumnType("float");

                    b.Property<string>("BudgetPeriod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("NeedsPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SavingsPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("WantsPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Budget");
                });

            modelBuilder.Entity("Project_PiggyPro.Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSystemCategory")
                        .HasColumnType("bit");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Housing & Rent",
                            CategoryType = "Expense",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 16, 15, 58, 51, 71, DateTimeKind.Local).AddTicks(6740),
                            DateUpdated = new DateTime(2026, 1, 16, 15, 58, 51, 71, DateTimeKind.Local).AddTicks(6756),
                            IsSystemCategory = true,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Groceries",
                            CategoryType = "Expense",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 16, 15, 58, 51, 71, DateTimeKind.Local).AddTicks(6758),
                            DateUpdated = new DateTime(2026, 1, 16, 15, 58, 51, 71, DateTimeKind.Local).AddTicks(6759),
                            IsSystemCategory = true,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Utilities",
                            CategoryType = "Expense",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 16, 15, 58, 51, 71, DateTimeKind.Local).AddTicks(6760),
                            DateUpdated = new DateTime(2026, 1, 16, 15, 58, 51, 71, DateTimeKind.Local).AddTicks(6761),
                            IsSystemCategory = true,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Transportation",
                            CategoryType = "Expense",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 16, 15, 58, 51, 71, DateTimeKind.Local).AddTicks(6762),
                            DateUpdated = new DateTime(2026, 1, 16, 15, 58, 51, 71, DateTimeKind.Local).AddTicks(6763),
                            IsSystemCategory = true,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "Healthcare",
                            CategoryType = "Expense",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 16, 15, 58, 51, 71, DateTimeKind.Local).AddTicks(6764),
                            DateUpdated = new DateTime(2026, 1, 16, 15, 58, 51, 71, DateTimeKind.Local).AddTicks(6765),
                            IsSystemCategory = true,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 6,
                            CategoryName = "Dining Out",
                            CategoryType = "Expense",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 16, 15, 58, 51, 71, DateTimeKind.Local).AddTicks(6766),
                            DateUpdated = new DateTime(2026, 1, 16, 15, 58, 51, 71, DateTimeKind.Local).AddTicks(6767),
                            IsSystemCategory = true,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 7,
                            CategoryName = "Entertainment",
                            CategoryType = "Expense",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 16, 15, 58, 51, 71, DateTimeKind.Local).AddTicks(6768),
                            DateUpdated = new DateTime(2026, 1, 16, 15, 58, 51, 71, DateTimeKind.Local).AddTicks(6769),
                            IsSystemCategory = true,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 8,
                            CategoryName = "Shopping",
                            CategoryType = "Expense",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 16, 15, 58, 51, 71, DateTimeKind.Local).AddTicks(6770),
                            DateUpdated = new DateTime(2026, 1, 16, 15, 58, 51, 71, DateTimeKind.Local).AddTicks(6771),
                            IsSystemCategory = true,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 9,
                            CategoryName = "Hobbies",
                            CategoryType = "Expense",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 16, 15, 58, 51, 71, DateTimeKind.Local).AddTicks(6772),
                            DateUpdated = new DateTime(2026, 1, 16, 15, 58, 51, 71, DateTimeKind.Local).AddTicks(6773),
                            IsSystemCategory = true,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 10,
                            CategoryName = "Savings",
                            CategoryType = "Expense",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 16, 15, 58, 51, 71, DateTimeKind.Local).AddTicks(6775),
                            DateUpdated = new DateTime(2026, 1, 16, 15, 58, 51, 71, DateTimeKind.Local).AddTicks(6775),
                            IsSystemCategory = true,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 11,
                            CategoryName = "Investments",
                            CategoryType = "Expense",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 16, 15, 58, 51, 71, DateTimeKind.Local).AddTicks(6776),
                            DateUpdated = new DateTime(2026, 1, 16, 15, 58, 51, 71, DateTimeKind.Local).AddTicks(6777),
                            IsSystemCategory = true,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 12,
                            CategoryName = "Emergency Fund",
                            CategoryType = "Expense",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 16, 15, 58, 51, 71, DateTimeKind.Local).AddTicks(6778),
                            DateUpdated = new DateTime(2026, 1, 16, 15, 58, 51, 71, DateTimeKind.Local).AddTicks(6779),
                            IsSystemCategory = true,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 13,
                            CategoryName = "Other Expenses",
                            CategoryType = "Expense",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 16, 15, 58, 51, 71, DateTimeKind.Local).AddTicks(6780),
                            DateUpdated = new DateTime(2026, 1, 16, 15, 58, 51, 71, DateTimeKind.Local).AddTicks(6781),
                            IsSystemCategory = true,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 14,
                            CategoryName = "Salary",
                            CategoryType = "Income",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 16, 15, 58, 51, 71, DateTimeKind.Local).AddTicks(6782),
                            DateUpdated = new DateTime(2026, 1, 16, 15, 58, 51, 71, DateTimeKind.Local).AddTicks(6783),
                            IsSystemCategory = true,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 15,
                            CategoryName = "Freelance",
                            CategoryType = "Income",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 16, 15, 58, 51, 71, DateTimeKind.Local).AddTicks(6784),
                            DateUpdated = new DateTime(2026, 1, 16, 15, 58, 51, 71, DateTimeKind.Local).AddTicks(6785),
                            IsSystemCategory = true,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 16,
                            CategoryName = "Investment Income",
                            CategoryType = "Income",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 16, 15, 58, 51, 71, DateTimeKind.Local).AddTicks(6786),
                            DateUpdated = new DateTime(2026, 1, 16, 15, 58, 51, 71, DateTimeKind.Local).AddTicks(6787),
                            IsSystemCategory = true,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 17,
                            CategoryName = "Gift/Bonus",
                            CategoryType = "Income",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 16, 15, 58, 51, 71, DateTimeKind.Local).AddTicks(6788),
                            DateUpdated = new DateTime(2026, 1, 16, 15, 58, 51, 71, DateTimeKind.Local).AddTicks(6789),
                            IsSystemCategory = true,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 18,
                            CategoryName = "Other Income",
                            CategoryType = "Income",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 16, 15, 58, 51, 71, DateTimeKind.Local).AddTicks(6790),
                            DateUpdated = new DateTime(2026, 1, 16, 15, 58, 51, 71, DateTimeKind.Local).AddTicks(6791),
                            IsSystemCategory = true,
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("Project_PiggyPro.Domain.Goal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CurrentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("GoalName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TargetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TargetDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Goal");
                });

            modelBuilder.Entity("Project_PiggyPro.Domain.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotificationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("Project_PiggyPro.Domain.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Transaction");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Project_PiggyPro.Data.Project_PiggyProUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Project_PiggyPro.Data.Project_PiggyProUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project_PiggyPro.Data.Project_PiggyProUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Project_PiggyPro.Data.Project_PiggyProUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Project_PiggyPro.Domain.Budget", b =>
                {
                    b.HasOne("Project_PiggyPro.Domain.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
